### ISSUE TITLE
Compatibility issues when adding Autologistic.jl

### ISSUE THREAD

**Issue by anmiri** [kramsretlow/Autologistic.jl#11]
Hi,
I would like to use Autologistic.jl, but I cannot add the package. I get this error message when I try:

```
ERROR: Unsatisfiable requirements detected for package Autologistic [4d03fd4d]:
 Autologistic [4d03fd4d] log:
 ├─possible versions are: 0.4.0-0.4.2 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.4.0-0.4.2
 └─restricted by compatibility requirements with CSV [336ed68f] to versions: uninstalled — no versions left
   └─CSV [336ed68f] log:
     ├─possible versions are: [0.3.0-0.3.1, 0.4.0-0.4.3, 0.5.0-0.5.26, 0.6.0-0.6.2, 0.7.0-0.7.10, 0.8.0-0.8.2] or uninstalled
     └─restricted to versions 0.7.3 by an explicit requirement, leaving only versions 0.7.3
```

I made sure my version of CSV is pinned at 0.7.3, so it should be possible to add Autologistic. Does it have any other major dependencies not mentioned here or is it perhaps not compatible with later versions of Julia? (I'm using v 1.5).

**Comment by kramsretlow** [comment]
Hello, thank you for raising this issue.

I was able to add and use Autologistic.jl in a fresh environment in Julia 1.5.2, so no problem there, I think.

A few of the dependencies (including CSV) were not updated for quite a while and had got pretty far behind the current versions. So I've updated the dependencies in Project.toml in Autologistic v.0.4.3. 

I imagine that will solve the problem--please let me know if it does or does not!

**Comment by anmiri** [comment]
Hello, thank you for your quick response. The update worked, and now I can install the package with no problems. Thanks!

**Comment by kramsretlow** [comment]
Great, happy modelling!
