### ISSUE TITLE
LightGraphs.jl is archived. Move to the Graphs.jl fork?

### ISSUE THREAD

**Issue by ikosmidis** [kramsretlow/Autologistic.jl#14]
I am facing some issues where Autologistic.jl expects LightGraphs.SimpleGraph objects and not Graphs.SimpleGraph ones. Given that  LightGraphs.jl is not actively developed anymore (see https://github.com/sbromberger/LightGraphs.jl), would it be easy to move dependencies to the Graphs.jl fork (https://github.com/JuliaGraphs/Graphs.jl)? Thanks

**Comment by kramsretlow** [comment]
Thank you for bringing this to my attention, I will work on it in the coming days.

**Comment by kramsretlow** [comment]
The change is made in v0.5.1. I'll close this issue but please let me know if anything doesn't work as expected.

**Comment by ikosmidis** [comment]
Thanks. Things seem to work as before; will re-open if I spot any issues. Thanks for such a great work (saved me quite some time, especially your careful work on samplers!)
