### ISSUE TITLE
How to perform predictions with ALRsimple?

### ISSUE THREAD

**Issue by juliohm** [kramsretlow/Autologistic.jl#8]
I followed the spatial data example in the docs, and could get the fitted object perfectly.

How to use the fitted model to make predictions? I am looking for the function `predict(fittedALR, newgrid)`.

**Comment by juliohm** [comment]
Below is the script with the fitted model so far:

```julia
using Autologistic

df = Autologistic.datasets("hydrocotyle")

locations = [(df.X[i], df.Y[i]) for i in 1:size(df,1)]
g = makespatialgraph(locations, 1.0)

Xmatrix = [ones(2995) df.altitude df.temperature]

hydro = ALRsimple(g.G, Xmatrix, Y=df.obs[:])

fit1 = fit_pl!(hydro, allow_f_increases=true)
```

**Comment by kramsretlow** [comment]
Actually there is no single function for doing it. Just to make sure we're talking about the same thing, the model in Autologistic.jl is fundamentally linked to the graph, not any spatial coordinates associated with the vertices. So if `newgrid` is some different set of coordinates, this isn't really compatible with the package design. 

On the other hand if you have a new set of covariates, like `newXmatrix`, you can construct a new model instance with those covariates and generate a prediction.  "Prediction" could mean an expected value, or a probability of taking the high level, or some people might want the MAP estimate (maximum a posteriori--the most probable configuration of states).  The first two of these can be done approximately, by sampling, like

```julia
newhydro = deepcopy(hydro)    #a copy of the fitted model
newXmatrix = Xmatrix .+ [zeros(2995) randn(2995,2)]    #perturbed predictors
newhydro.unary.X .= newXmatrix
realizations = sample(newhydro, 1000)
prob = mapslices(x -> sum(x.==1.0)/1000, realizations, dims=2)
```

After this, `prob` holds 2995 estimates of the probability of getting a +1 at each vertex in the graph.  It's clunky this way but I never had the need to do this so I never made a function for it.

The MAP would be nice to have but I never worked on it; I don't think it can be efficiently computed for all parts of the parameter space (or for all graph structures). It's future work, I guess.

I hope the above makes sense.

**Comment by juliohm** [comment]
> the model in Autologistic.jl is fundamentally linked to the graph, not any spatial coordinates associated with the vertices. So if `newgrid` is some different set of coordinates, this isn't really compatible with the package design.

Makes sense, maybe I am confusing things, will read your paper once again to double check the concepts. Initially I thought that like with simple logistic regression, we would be able to first fit the ALR to some training covariates, and then predict given new features on the same grid of coordinates.

> On the other hand if you have a new set of covariates, like `newXmatrix`, you can construct a new model instance with those covariates and generate a prediction. "Prediction" could mean an expected value, or a probability of taking the high level, or some people might want the MAP estimate (maximum a posteriori--the most probable configuration of states). The first two of these can be done approximately, by sampling

Nice! This is getting close to what I had in mind. :) Will try locally when I find some time, and will get back if some concept is not clear. BTW, maybe a redesign of the types and infrastructure could facilitate these types of usage.
